branches:
  only:
  - dev
language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm run build
after_success:
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"
  - git checkout -b master
  - git add build
  - git commit --message "[skip ci]"
  - git remote add origin-build https://${GH_TOKEN}@github.com/felipemarinho97/github-travis.git > /dev/null 2>&1
  - git push --quiet --set-upstream origin-build master
deploy:
  provider: pages
  skip_cleanup: true
  target-branch: master
  github_token: $github_token
  keep-history: true
  on:
    branch: master
