language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - ./build.sh
after_success:
  - MESSAGE=$(git log --format=%B -n 1 $TRAVIS_COMMIT)
  - git add build
  - git commit -m ${MESSAGE}
  - git push "https://${github_token}@github.com/felipemarinho97/github-travis.git" master
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master
